version: '3.8'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=e-learning-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/codigo
    ports:
      - "8000:8000"
    depends_on:
      - db

  celery:
    build: .
    command: celery -A e_learning worker --loglevel=info
    volumes:
      - .:/codigo
    depends_on:
      - db
      - web

  redis:
    image: "redis:alpine"

    
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"


